table Combustible

	column 'month'
		dataType: string
		summarizeBy: none
		sourceColumn: month

	column 'vehicle_type'
		dataType: string
		summarizeBy: none
		sourceColumn: vehicle_type

	column 'fuel_type'
		dataType: string
		summarizeBy: none
		sourceColumn: fuel_type

	column 'trip_count'
		dataType: double
		summarizeBy: none
		sourceColumn: trip_count

	column 'total_fuel_liters'
		dataType: double
		summarizeBy: none
		sourceColumn: total_fuel_liters

	column 'total_distance_km'
		dataType: double
		summarizeBy: none
		sourceColumn: total_distance_km

	measure KPI_trip_count = SUM(Combustible[trip_count])
		formatString: #,0.00
		displayFolder: Indicadores

	measure KPI_total_fuel_liters = SUM(Combustible[total_fuel_liters])
		formatString: #,0.00
		displayFolder: Indicadores

	measure KPI_total_distance_km = SUM(Combustible[total_distance_km])
		formatString: #,0.00
		displayFolder: Indicadores

	measure KPI_Eficiencia = DIVIDE(SUM(Combustible[total_fuel_liters])*100, SUM(Combustible[total_distance_km]))
		formatString: #,0.00
		displayFolder: Indicadores

	partition Combustible = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "Combustible.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Headers = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Headers, {{"month", type text}, {"vehicle_type", type text}, {"fuel_type", type text}, {"trip_count", type number}, {"total_fuel_liters", type number}, {"total_distance_km", type number}}, "en-US")
				in
				    Typed
